Debian package fix

diff --git a/debian/flexiproxy-core.postrm b/debian/flexiproxy-core.postrm
--- a/debian/flexiproxy-core.postrm
+++ b/debian/flexiproxy-core.postrm
@@ -1,17 +1,42 @@
 #!/bin/sh
 # postrm script for flexiproxy
-
 set -e
 
-if [ -f /usr/share/flexiproxy/composer.lock ] ; then
-    rm -f /usr/share/flexiproxy/composer.lock
-fi
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
+# for details, see /usr/doc/packaging-manual/
 
-if [ -f /var/lib/flexiproxy/autoload.php ] ; then
-    rm -rf /var/lib/flexiproxy/
-fi
+case "$1" in
+       purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
+        if [ -f /usr/share/flexiproxy/composer.lock ] ; then
+            echo    postrm -rfv /usr/share/flexiproxy
+            rm -rfv /usr/share/flexiproxy
+        fi
 
+        if [ -f /var/lib/flexiproxy/autoload.php  ] ; then
+            echo    postrm -rfv /var/lib/flexiproxy/
+            rm -rfv /var/lib/flexiproxy/
+        fi
+
+        ;;
+
+       upgrade)
+        ;;
+
+    *)
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 0
+
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
-
-exit 0
